import {
  BadgeDollarSign,
  Building2,
  FileText,
  Funnel,
  LayoutDashboard,
  Package,
  Receipt,
  Settings,
  Shield,
  Star,
  Stethoscope,
  Users,
  BarChart3,
  Calendar,
} from 'lucide-react';

export const navIcons = {
  'layout-dashboard': LayoutDashboard,
  'building-2': Building2,
  users: Users,
  package: Package,
  funnel: Funnel,
  'file-text': FileText,
  'badge-dollar-sign': BadgeDollarSign,
  stethoscope: Stethoscope,
  receipt: Receipt,
  star: Star,
  shield: Shield,
  settings: Settings,
  'bar-chart': BarChart3,
  calendar: Calendar,
};
